### ISSUE TITLE
Support multiple monitors

### ISSUE THREAD

**Issue by beuaaa** [beuaaa/overlay_arrows_and_more#2]
If several monitors are used in different arrangements (secondary monitor above or below the primary monitor, secondary monitor to the left or right of the primary monitor, etc.) the coordinates must be relative to the primary monitor.

For example:
The primary monitor and the secondary monitor have the same resolution of 1920x1080, the primary monitor is below the secondary monitor.  Then:

- (0,0) is the top left corner of the primary monitor
- (1919,1079) is the bottom right corner of the primary monitor
- (0,-1080) is the top left corner of the secondary monitor
- (1919,-1) is the bottom right corner of the secondary monitor

Thanks to the latest pull request from USerik the current code is :
```python
		self.h_window = win32gui.CreateWindowEx(
			ex_style, wnd_class_atom,
			'OverlayWindow',
			style,
			0,  # x
			0,  # y
			win32api.GetSystemMetrics(win32con.SM_CXVIRTUALSCREEN),  # width
			win32api.GetSystemMetrics(win32con.SM_CYVIRTUALSCREEN),  # height
			None,  # hWndParent
			None,  # hMenu
			h_instance,
```			

I think we should do something like:
```python
		self.h_window = win32gui.CreateWindowEx(
			ex_style, wnd_class_atom,
			'OverlayWindow',
			style,
			win32api.GetSystemMetrics(win32con.SM_XVIRTUALSCREEN),  # x
			win32api.GetSystemMetrics(win32con.SM_YVIRTUALSCREEN),  # y
			win32api.GetSystemMetrics(win32con.SM_CXVIRTUALSCREEN),  # width
			win32api.GetSystemMetrics(win32con.SM_CYVIRTUALSCREEN),  # height
			None,  # hWndParent
			None,  # hMenu
			h_instance,
			None  # lpParam
```

Next, we need to know the coordinates of the primary monitor in the virtual screen so that we can transform the coordinates when drawing.

**Comment by beuaaa** [comment]
It seems that we only have to deal with cases where the monitors' work areas have negative coordinates:

```python
		monitors = win32api.EnumDisplayMonitors()
		x_min = min([win32api.GetMonitorInfo(monitor[0])['Work'][0] for monitor in monitors])
		y_min = min([win32api.GetMonitorInfo(monitor[0])['Work'][1] for monitor in monitors])
```

Then simply subtract the negative x_min and y_min from the coordinates of the drawn shapes.

I feel like you don't even need to know where the primary monitor is because it seems to always start at (0,0).

**Comment by USerik** [comment]
Have tested on my PCs, that works!
